allowBuilds:
  '@parcel/watcher': set this to true or false
  '@prisma/client': false
  '@prisma/engines': false
  '@scarf/scarf': set this to true or false
  esbuild: false
  prisma: false
  unrs-resolver: set this to true or false
